import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

const outPath = resolve(root, 'src', 'app', 'version.ts');
const content =
  `// AUTO-GENERATED by scripts/generate-version.mjs - do not edit by hand.\n` +
  `// Single source of truth is the "version" field in package.json.\n` +
  `export const APP_VERSION = '${pkg.version}';\n`;

writeFileSync(outPath, content);
console.log(`Wrote ${outPath} (v${pkg.version})`);
